version: '3.8'

services:
  file-uploader:
    build: .
    container_name: file_uploader_service
    ports:
      - "3030:3027"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./token_store.db:/usr/src/app/token_store.db

volumes:
  token_store:
    driver: local
    driver_opts:
      type: none
      device: ./token_store.db
      o: bind
